[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
dice_duel = "7xfkbzEMJ31jPUqZoJ3EXrU72LiAw1wGKupGqmdZdoMM"
simple-vrf-test = "7ih1HPx6QbhjpE5Bi7SWB4xsyfbHbQnjLWr6Vf67GAjg"
vrf-test = "Hc2XsRggfBvCvSKEE3w6pPWwjmsttefGx6bcb2VhxHLD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/dice-duel"]
