import { appendFileSync, readFileSync, readdirSync } from "fs";
import { join } from "path";
import { rootNodeFromAnchor } from "@codama/nodes-from-anchor";
import { renderVisitor } from "@codama/renderers-js";
// scripts/codegen-svm.mjs
import { createFromRoot } from "codama";

const idlDir = "generated/idl";
const outDir = "generated/clients/svm";

const idlFiles = readdirSync(idlDir).filter((f) => f.endsWith(".json"));

if (idlFiles.length === 0) {
	console.error(`No IDL files found in ${idlDir}. Run 'pnpm build:svm' first.`);
	process.exit(1);
}

for (const file of idlFiles) {
	try {
		const idl = JSON.parse(readFileSync(join(idlDir, file), "utf8"));
		const programName = file.replace(".json", "").replace(/_/g, "-");

		// Pre-process IDL: remove PDA definition from prev_escrow in initiate_wager.
		// Codama cannot resolve a PDA seed that references an optional account.
		// See: https://github.com/codama-idl/codama/issues/180
		const initiateWager = idl.instructions?.find(
			(i) => i.name === "initiate_wager",
		);
		if (initiateWager) {
			const prevEscrow = initiateWager.accounts?.find(
				(a) => a.name === "prev_escrow",
			);
			if (prevEscrow) {
				delete prevEscrow.pda;
			}
		}

		const codama = createFromRoot(rootNodeFromAnchor(idl));

		codama.accept(
			renderVisitor(join(outDir, programName), {
				dependencyMap: {},
			}),
		);

		// Append pdas re-export to index.ts (pdas.ts is manually maintained)
		const indexPath = join(outDir, programName, "index.ts");
		const indexContent = readFileSync(indexPath, "utf8");
		if (!indexContent.includes("./pdas")) {
			appendFileSync(
				indexPath,
				'\n// Manual addition — pdas.ts is not auto-generated by Codama\nexport * from "./pdas";\n',
			);
		}

		console.log(
			`Generated client for ${programName} → ${outDir}/${programName}/`,
		);
	} catch (err) {
		console.error(`Failed to generate client for ${file}:`, err);
		process.exit(1);
	}
}
